### ISSUE TITLE
POK-Manager changes user permission for my authorized_keys

### ISSUE THREAD

**Issue by sMuve** [Acekorneya/Ark-Survival-Ascended-Server#53]
Hi there,
always when I do create an instance the POK-manager is changing the permission for my authorized_keys which will ofc break my SSH access.
![grafik](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/25771494/97dfc78c-e9e1-4edc-83f5-16d7370e1351)

As I don't see issues regarding this problem I would assume I do misuse the tool somehow. Can you maybe help with it?

PS: The dir `.ssh` had the owner `root:pokgroup`

**Comment by sMuve** [comment]
Oh and for the `.ssh` dir the perrmisions where `root:pokgroup`

**Comment by Acekorneya** [comment]
Just don’t have that file inside the same folder location as the POK-manager.sh. The reason why it changes is because, for the whole storage system to work and store the server files on the host machine, we need that folder to have a PUID and PGID of 1000. Otherwise, nothing will work as it won’t have permission to modify the save files, etc. So, every time you create an instance, a function is run to ensure all the folders and files inside or in the same location as POK-manager will have their permissions changed to 1000.
