### ISSUE TITLE
Server stuck in loading loop on mods

### ISSUE THREAD

**Issue by Gurticus** [Acekorneya/Ark-Survival-Ascended-Server#59]
Hey after small errors ive come to a point where the server is stuck in a loop booting, it gets to the mods and loads / says valid then loops back round

![Screenshot 2024-07-31 011416](https://github.com/user-attachments/assets/0f7918b6-a761-4c87-b521-ffbdf7f407e6)

**Comment by Acekorneya** [comment]
Thanks for bringing this to my attention! From what I can see, the server is getting stuck in a loop where it validates the mods but then immediately restarts. This could be due to a mod compatibility issue, server configuration, or resource limits on your system.

Here’s what I’d suggest to troubleshoot:
1. **Check the Server Logs**: Look at the full logs to see if there’s an error right before the server attempts to restart. This might give us a clue.
2. **Mod Testing**: Try disabling mods one by one to see if the issue persists. It could be a specific mod causing the problem.
3. **Resource Allocation**: If your system is low on resources, increasing the memory or CPU allocation might help.
4. **Mod Compatibility**: Ensure all your mods are up to date and compatible with the current server version.

I haven’t encountered this issue with the mods I’m using, but different setups can lead to different problems. Let me know if any of these steps help, or if you find anything specific in the logs!
