### ISSUE TITLE
Backups getting overwritten

### ISSUE THREAD

**Issue by chronic414z** [Acekorneya/Ark-Survival-Ascended-Server#62]
I run hourly backups on my server. And while checking the backups I noticed that some were missing. They were overwritten because of the timestamp that is used. Can you please change the timestamp generation from 12 hour format to 24 hour format (%H instead of %I)?

**Comment by Acekorneya** [comment]
I understand your concern about backups potentially being overwritten due to the 12-hour timestamp format. The backup system generates unique filenames by including minutes and seconds in the timestamp, which should prevent overwriting under normal circumstances.

However, if you’re seeing backups disappear, it might be due to the retention settings in the configuration file. You can adjust the MAX_BACKUPS and MAX_SIZE_GB values in /config/POK-manager/[instance_name].conf to increase the number of backups retained and the total storage allocated. This should help ensure that all necessary backups are kept

**Comment by chronic414z** [comment]
No, they dont disappear due to retention policies. It's because of the timestamp. Here is an actual example:


> -rw-r--r-- 1 chronic chronic 376M 20. Aug 22:01 island_backup_2024-08-20_10-00-31.tar.gz
-rw-r--r-- 1 chronic chronic 376M 20. Aug 21:00 island_backup_2024-08-20_09-00-28.tar.gz
-rw-r--r-- 1 chronic chronic 375M 20. Aug 20:00 island_backup_2024-08-20_08-00-28.tar.gz
-rw-r--r-- 1 chronic chronic 378M 20. Aug 19:01 island_backup_2024-08-20_07-00-32.tar.gz
-rw-r--r-- 1 chronic chronic 376M 20. Aug 18:01 island_backup_2024-08-20_06-00-28.tar.gz
-rw-r--r-- 1 chronic chronic 380M 20. Aug 17:01 island_backup_2024-08-20_05-00-36.tar.gz
-rw-r--r-- 1 chronic chronic 380M 20. Aug 16:01 island_backup_2024-08-20_04-00-30.tar.gz
-rw-r--r-- 1 chronic chronic 382M 20. Aug 15:01 island_backup_2024-08-20_03-00-29.tar.gz
-rw-r--r-- 1 chronic chronic 382M 20. Aug 14:01 island_backup_2024-08-20_02-00-30.tar.gz
-rw-r--r-- 1 chronic chronic 384M 20. Aug 13:01 island_backup_2024-08-20_01-00-29.tar.gz
-rw-r--r-- 1 chronic chronic 384M 20. Aug 12:01 island_backup_2024-08-20_12-00-29.tar.gz
-rw-r--r-- 1 chronic chronic 386M 20. Aug 11:01 island_backup_2024-08-20_11-00-28.tar.gz
-rw-r--r-- 1 chronic chronic 386M 20. Aug 10:01 island_backup_2024-08-20_10-00-28.tar.gz
-rw-r--r-- 1 chronic chronic 387M 20. Aug 08:01 island_backup_2024-08-20_08-00-29.tar.gz
-rw-r--r-- 1 chronic chronic 388M 20. Aug 07:00 island_backup_2024-08-20_07-00-28.tar.gz


The backup of 09 o'clock is missing. And when you look at the file names there is often only 1 second difference between them. So the possibility to get the same name is fairly high.

**Comment by Acekorneya** [comment]
Thank you for providing the detailed information. I see that the issue is indeed related to the timestamp format, which could cause backups to overwrite each other due to similar timestamps when using a 12-hour format.

I’ve updated the script to use a 24-hour format for the timestamp, which should help prevent this problem by ensuring that each backup has a unique name.
